/**
 * Audio sprite sound type.
 *
 * @typedef {object} Vsengine.Types.Sound.AudioSpriteSound
 * @since 3.0.0
 *
 * @property {object} spritemap - Local reference to 'spritemap' object form json file generated by audiosprite tool.
 */
